import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Toaster 
  position="top-right" 
  toastOptions={{
    classNames: {
      toast: "group border border-zinc-200/60 bg-white/80 backdrop-blur-2xl shadow-2xl dark:border-white/10 dark:bg-zinc-950/80 rounded-2xl p-4",
      title: "text-sm font-semibold text-zinc-900 dark:text-zinc-100",
      description: "text-xs text-zinc-500 dark:text-zinc-400",
      success: "border-emerald-200/60 bg-emerald-50/80 text-emerald-600 dark:border-emerald-500/20 dark:bg-emerald-500/10 dark:text-emerald-400",
      error: "border-red-200/60 bg-red-50/80 text-red-600 dark:border-red-500/20 dark:bg-red-500/10 dark:text-red-400",
    },
  }} 
/>
      </body>
    </html>
  );
}
